### ISSUE TITLE
行数栏存在bug，图标很小

### ISSUE THREAD

**Issue by ctrlctrlctrlctrl** [lyflexi/feignx-plugin#1]
所有的feign类都是这样
![image](https://github.com/user-attachments/assets/2df16da6-ef28-4bfd-a72b-3f8d1ecff84d)

**Comment by lyflexi** [comment]
感谢提问。

feignx的icon是svg格式，它在1920*1080分辨率下是正常显示的，我花费了1个小时去检查了jetbrains原生的几个与icon有关的接口如# RelatedItemLineMarkerProvider、# NavigationGutterIconBuilder、# IconLoader，暂未找到自适应icon大小的配置项。

不同于png/jpg，按理说svg天然的支持自适应。

这个问题我会向官方提问，有结果我会在这里答复

**Comment by ctrlctrlctrlctrl** [comment]
感谢回复������



***@***.***
 
发件人： 月半大熊猫
发送时间： 2024-11-11 13:27
收件人： lyflexi/feignx-plugin
抄送： ctrlctrlctrlctrl; Author
主题： Re: [lyflexi/feignx-plugin] 行数栏存在bug，图标很小 (Issue #1)
感谢提问。
feignx的icon是svg格式，它在1920*1080分辨率下是正常显示的，我花费了1个小时去检查了jetbrains原生的几个与icon有关的接口如# RelatedItemLineMarkerProvider、# NavigationGutterIconBuilder、# IconLoader，暂未找到自适应icon大小的配置项。
不同于png/jpg，按理说svg天然的支持自适应。
这个问题我会向官方提问，有结果我会在这里答复

**Comment by JiangLxx** [comment]
需要额外配置吗，没有图标展示呢

**Comment by lyflexi** [comment]
@JiangLxx 不需要额外配置，方便贴出您的feign类以及controller类让我看看么

**Comment by lyflexi** [comment]
> 需要额外配置吗，没有图标展示呢

严格的路由规则如下：（这也是SpringCloud中有效OpenFeign接口本身的规则）

Feign接口方配置，注意有先后顺序：
1. @FeignClient注解中的path值（可选）
2. Feign接口方法上@ RequestMapping中的url值（必选）

目标服务方MVC配置， 注意先后顺序：
1. server.servlet.context-path值（可选）
2. spring.mvc.servlet.path值（可选）
3. 目标Controller的@ RequestMapping注解值（可选）
4. 目标Controller方法上@ RequestMapping注解值（必选）

```
if (StringUtils.equal(Feign接口方配置拼接，目标服务方MVC配置拼接)) return "有效匹配，显示导航flutter icon"
```

@ GetMapping、@PostMapping、@DeleteMapping、@PutMapping同理
