### ISSUE TITLE
feignClient属性加了path就不显示跳转按钮

### ISSUE THREAD

**Issue by ccyy1155** [lyflexi/feignx-plugin#2]
feignClient属性加了path就不显示跳转按钮，不加属性值就有了跳转按钮

**Comment by ccyy1155** [comment]
![屏幕截图 2024-11-19 143629](https://github.com/user-attachments/assets/9f563e9d-6b53-4ffa-ae97-5cef32e12474)

**Comment by ccyy1155** [comment]
![屏幕截图 2024-11-19 143955](https://github.com/user-attachments/assets/9377be99-dc70-40d3-9601-520b4b191822)

**Comment by lyflexi** [comment]
请提供下controller代码，自己controller所在模块的yml/properties配置

**Comment by lyflexi** [comment]
严格的路由规则如下：（这也是SpringCloud中有效OpenFeign接口本身的规则）

Feign接口方配置，注意有先后顺序：
1. @FeignClient注解中的path值（可选）
2. Feign接口方法上@ RequestMapping中的url值（必选）

目标服务方MVC配置， 注意先后顺序：
1. server.servlet.context-path值（可选）
2. spring.mvc.servlet.path值（可选）
3. 目标Controller的@ RequestMapping注解值（可选）
4. 目标Controller方法上@ RequestMapping注解值（必选）

```
if (StringUtils.equal(Feign接口方配置拼接，目标服务方MVC配置拼接)) return "有效匹配，显示导航flutter icon"
```

@ GetMapping、@PostMapping、@DeleteMapping、@PutMapping同理

**Comment by ccyy1155** [comment]
好的，谢谢哈，我在试试，有点忙，加上网络原因，没来的及回复
