### ISSUE TITLE
切换主题后图标不显示

### ISSUE THREAD

**Issue by SghSean** [lyflexi/feignx-plugin#3]
可以显示主题
<img width="124" alt="image" src="https://github.com/user-attachments/assets/41403425-017a-4244-bc77-97baeefb2589">

不可显示主题
<img width="174" alt="image" src="https://github.com/user-attachments/assets/f1305ad7-d3ee-44dd-92f8-461df1850f5e">

**Comment by lyflexi** [comment]
你好，feignx适配了最新版IDEA的Light主题，欢迎在IDEA内在线更新至4.1.1版本（三天后上线），或者提前安装离线版体验！
https://github.com/lyflexi/feignx-plugin/releases/tag/v4.1.1
![image](https://github.com/user-attachments/assets/caa872a8-ed75-4f27-b2cb-da9c00cd225c)
